import React, { useState } from 'react';
import { 
  CheckSquare, 
  CheckCircle2, 
  Phone, 
  IdCard, 
  Clock, 
  Printer, 
  Copy, 
  Check, 
  AlertCircle, 
  HeartHandshake, 
  HelpCircle 
} from 'lucide-react';
import { ACCEPTABLE_IDS, DEFAULT_VOTER_PLAN_ITEMS } from '../data/electionData';
import { VoterPlanItem } from '../types';

export const VoterPlan: React.FC = () => {
  const [items, setItems] = useState<VoterPlanItem[]>(DEFAULT_VOTER_PLAN_ITEMS);
  const [targetTime, setTargetTime] = useState<string>('08:00 AM (Cool morning slot)');
  const [selectedIdType, setSelectedIdType] = useState<string>('Voter ID Card (EPIC)');
  const [notes, setNotes] = useState<string>('');
  const [copied, setCopied] = useState<boolean>(false);

  const toggleItem = (id: string) => {
    setItems((prev) =>
      prev.map((item) => (item.id === id ? { ...item, completed: !item.completed } : item))
    );
  };

  const completedCount = items.filter((i) => i.completed).length;
  const progressPercent = Math.round((completedCount / items.length) * 100);

  const handleCopyPlan = () => {
    const text = `MY ELECTION DAY PLAN:
- Prepared Photo ID: ${selectedIdType}
- Target Voting Time: ${targetTime}
- Checklist Status: ${completedCount}/${items.length} completed (${progressPercent}%)
- Personal Notes: ${notes || 'None'}
- Election Helpline: 1950
(Generated by CivicPulse Election Awareness Platform)`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="bg-white rounded-2xl p-6 sm:p-8 border border-slate-200 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-full bg-blue-50 text-blue-700 text-xs font-semibold border border-blue-200 mb-2">
            <CheckSquare className="w-3.5 h-3.5" />
            Personal Election Day Planner
          </div>
          <h2 className="text-2xl font-bold font-heading text-slate-900">
            Plan Your Voting Day
          </h2>
          <p className="text-slate-600 text-xs sm:text-sm mt-1 max-w-2xl">
            Voters who prepare ahead—by verifying their registration, picking an early time slot, and bringing the correct photo ID—experience smooth, stress-free voting.
          </p>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          <button
            id="copy-plan-btn"
            onClick={handleCopyPlan}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold border border-slate-300 transition-colors"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied to Clipboard!' : 'Copy Plan Summary'}
          </button>
          <button
            id="print-plan-btn"
            onClick={() => window.print()}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold shadow-xs transition-colors"
          >
            <Printer className="w-4 h-4" />
            Print Checklist
          </button>
        </div>
      </div>

      {/* Progress Card */}
      <div className="bg-gradient-to-r from-blue-600 to-indigo-700 rounded-2xl p-6 text-white shadow-md">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-3">
          <div>
            <span className="text-xs font-bold uppercase tracking-wider text-blue-200">
              Voter Readiness Score
            </span>
            <h3 className="text-xl font-bold font-heading">
              {progressPercent === 100
                ? '🎉 You Are 100% Prepared to Cast Your Vote!'
                : `${progressPercent}% Election Day Ready`}
            </h3>
          </div>
          <span className="text-2xl font-bold font-mono">
            {completedCount} / {items.length} Tasks
          </span>
        </div>

        {/* Progress bar */}
        <div className="w-full h-2.5 bg-blue-900/40 rounded-full overflow-hidden border border-blue-400/30">
          <div
            className="h-full bg-emerald-400 transition-all duration-300 rounded-full"
            style={{ width: `${progressPercent}%` }}
          ></div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Checklist & Schedule (7 cols) */}
        <div className="lg:col-span-7 space-y-6">
          {/* Action Checklist */}
          <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-4">
            <h4 className="text-sm font-bold uppercase tracking-wider text-slate-600 flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-blue-600" />
              Essential Voting Day Checklist
            </h4>

            <div className="space-y-2.5">
              {items.map((item) => (
                <div
                  key={item.id}
                  id={`plan-item-${item.id}`}
                  onClick={() => toggleItem(item.id)}
                  className={`p-3.5 rounded-xl border cursor-pointer transition-all duration-150 flex items-start gap-3 ${
                    item.completed
                      ? 'bg-emerald-50/70 border-emerald-300/80 text-emerald-950'
                      : 'bg-white border-slate-200 hover:border-slate-300 text-slate-800'
                  }`}
                >
                  <div
                    className={`w-5 h-5 rounded-md border flex items-center justify-center shrink-0 mt-0.5 transition-colors ${
                      item.completed
                        ? 'bg-emerald-600 border-emerald-600 text-white'
                        : 'border-slate-300 bg-white'
                    }`}
                  >
                    {item.completed && <Check className="w-3.5 h-3.5" />}
                  </div>
                  <div className="grow">
                    <h5
                      className={`text-xs font-bold ${
                        item.completed ? 'line-through text-emerald-900' : 'text-slate-900'
                      }`}
                    >
                      {item.label}
                    </h5>
                    <p className="text-[11px] text-slate-500 mt-0.5">{item.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Target Time & Custom Notes */}
          <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-4">
            <h4 className="text-sm font-bold uppercase tracking-wider text-slate-600 flex items-center gap-2">
              <Clock className="w-4 h-4 text-blue-600" />
              Timing & Logistics
            </h4>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">
                  Target Voting Slot:
                </label>
                <select
                  value={targetTime}
                  onChange={(e) => setTargetTime(e.target.value)}
                  className="w-full text-xs bg-slate-50 border border-slate-200 rounded-xl p-2.5 font-medium focus:outline-hidden focus:ring-2 focus:ring-blue-500"
                >
                  <option value="07:30 AM (Opening Slot - No Queues)">07:30 AM (Opening Slot - No Queues)</option>
                  <option value="09:00 AM (Morning Slot)">09:00 AM (Morning Slot)</option>
                  <option value="01:30 PM (Midday Lull)">01:30 PM (Midday Lull)</option>
                  <option value="04:30 PM (Late Afternoon)">04:30 PM (Late Afternoon)</option>
                </select>
              </div>

              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">
                  Chosen Photo ID Document:
                </label>
                <select
                  value={selectedIdType}
                  onChange={(e) => setSelectedIdType(e.target.value)}
                  className="w-full text-xs bg-slate-50 border border-slate-200 rounded-xl p-2.5 font-medium focus:outline-hidden focus:ring-2 focus:ring-blue-500"
                >
                  {ACCEPTABLE_IDS.map((id, idx) => (
                    <option key={idx} value={id.name}>
                      {id.name}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <div>
              <label className="text-xs font-bold text-slate-700 block mb-1">
                Personal Reminders / Transport Notes:
              </label>
              <textarea
                rows={2}
                placeholder="e.g., Carpooling with Grandma at 8 AM, bringing water bottle..."
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                className="w-full text-xs bg-slate-50 border border-slate-200 rounded-xl p-3 focus:outline-hidden focus:ring-2 focus:ring-blue-500"
              ></textarea>
            </div>
          </div>
        </div>

        {/* Right: Acceptable IDs Reference & Helplines (5 cols) */}
        <div className="lg:col-span-5 space-y-6">
          {/* Acceptable IDs Accordion / List */}
          <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-4">
            <div className="flex items-center justify-between">
              <h4 className="text-sm font-bold uppercase tracking-wider text-slate-700 flex items-center gap-2">
                <IdCard className="w-4 h-4 text-blue-600" />
                Approved Photo IDs
              </h4>
              <span className="text-[10px] bg-blue-50 text-blue-700 px-2 py-0.5 rounded font-bold">
                10 Acceptable
              </span>
            </div>
            <p className="text-xs text-slate-500">
              Any ONE of the following official government documents can be presented at Station 1:
            </p>

            <div className="space-y-2 max-h-72 overflow-y-auto pr-1">
              {ACCEPTABLE_IDS.map((id, idx) => (
                <div
                  key={idx}
                  className={`p-2.5 rounded-lg border text-xs transition-colors ${
                    selectedIdType === id.name
                      ? 'bg-blue-50 border-blue-300 font-semibold text-blue-950'
                      : 'bg-slate-50/70 border-slate-200 text-slate-700'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-slate-900">{id.name}</span>
                    {selectedIdType === id.name && (
                      <span className="text-[10px] text-blue-600 font-bold uppercase">Selected</span>
                    )}
                  </div>
                  <p className="text-[11px] text-slate-500 mt-0.5">{id.desc}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Election Helplines & Disability Services */}
          <div className="p-5 rounded-2xl bg-slate-900 text-slate-200 border border-slate-800 space-y-4">
            <div className="flex items-center gap-2 text-white font-bold text-sm">
              <Phone className="w-4 h-4 text-emerald-400" />
              Official Helplines & Assistance
            </div>

            <div className="space-y-2.5 text-xs">
              <div className="p-3 rounded-xl bg-slate-800/90 border border-slate-700 flex items-center justify-between">
                <div>
                  <div className="font-bold text-white">National Voter Helpline</div>
                  <div className="text-[11px] text-slate-400">Toll-free 24/7 voter support</div>
                </div>
                <span className="font-mono text-base font-bold text-emerald-400 bg-slate-900 px-3 py-1 rounded-lg border border-slate-700">
                  1950
                </span>
              </div>

              <div className="p-3 rounded-xl bg-slate-800/90 border border-slate-700 flex items-center justify-between">
                <div>
                  <div className="font-bold text-white">Report Violations (cVigil)</div>
                  <div className="text-[11px] text-slate-400">Anonymous photo/video reporting of cash or liquor distribution</div>
                </div>
                <span className="text-[11px] font-bold text-blue-400 bg-blue-950 px-2.5 py-1 rounded-lg border border-blue-800">
                  cVigil App
                </span>
              </div>

              <div className="p-3 rounded-xl bg-slate-800/90 border border-slate-700 flex items-start gap-2.5">
                <HeartHandshake className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                <div className="text-[11px] text-slate-300 leading-relaxed">
                  <strong className="text-white">Accessible Voting Rights: </strong>
                  Wheelchairs, ramps, Braille on EVM balloting units, and companion assistance for visually impaired citizens are statutory rights at every polling station.
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
